name: debateseason_frontend_v1
description: "A new Flutter project."

version: 1.0.0+15

environment:
  sdk: '>=3.5.3 <3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # 통신
  http: ^1.2.2
  dio: ^5.7.0
  retrofit: ^4.4.2
  stomp_dart_client: ^2.1.1
  # build_runner
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # 보안
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.5
  # State
  get: ^4.6.6
  # UI
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  flutter_svg: ^2.0.17
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  any_link_preview: ^3.0.3
  flutter_linkify: ^6.0.0
  # Login
  firebase_core: ^3.10.0
  kakao_flutter_sdk_user: ^1.9.7+3
  sign_in_with_apple: ^6.1.4
  # ETC..
  intl: ^0.20.1
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  change_app_package_name: ^1.4.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  #GA
  amplitude_flutter: ^4.3.1
  package_info_plus: ^8.1.3

  # splash, icon
  flutter_native_splash: ^2.4.4
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  freezed: ^2.5.8
  json_serializable: ^6.9.3

icons_launcher:
  image_path: 'assets/images/ic_debate.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#161416'
      adaptive_foreground_image: 'assets/images/ic_debate.png'

    ios:
      enable: true
      image_path: 'assets/images/ic_debate.png'
      adaptive_background_color: '#161416'


flutter_native_splash:
  color: "#161416"
  image: assets/images/ic_debate.png
  android_12:
    icon_background_color: "#161416"

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
