import 'province_type.dart';

class DistrictType {
  final String code;
  final String name;
  final ProvinceType provinceType;

  const DistrictType._(this.code, this.name, this.provinceType);

  static const List<DistrictType> seoul = [
    DistrictType._("11010", "종로구", ProvinceType.seoul),
    DistrictType._("11020", "중구", ProvinceType.seoul),
    DistrictType._("11030", "용산구", ProvinceType.seoul),
    DistrictType._("11040", "성동구", ProvinceType.seoul),
    DistrictType._("11050", "광진구", ProvinceType.seoul),
    DistrictType._("11060", "동대문구", ProvinceType.seoul),
    DistrictType._("11070", "중랑구", ProvinceType.seoul),
    DistrictType._("11080", "성북구", ProvinceType.seoul),
    DistrictType._("11090", "강북구", ProvinceType.seoul),
    DistrictType._("11100", "도봉구", ProvinceType.seoul),
    DistrictType._("11110", "노원구", ProvinceType.seoul),
    DistrictType._("11120", "은평구", ProvinceType.seoul),
    DistrictType._("11130", "서대문구", ProvinceType.seoul),
    DistrictType._("11140", "마포구", ProvinceType.seoul),
    DistrictType._("11150", "양천구", ProvinceType.seoul),
    DistrictType._("11160", "강서구", ProvinceType.seoul),
    DistrictType._("11170", "구로구", ProvinceType.seoul),
    DistrictType._("11180", "금천구", ProvinceType.seoul),
    DistrictType._("11190", "영등포구", ProvinceType.seoul),
    DistrictType._("11200", "동작구", ProvinceType.seoul),
    DistrictType._("11210", "관악구", ProvinceType.seoul),
    DistrictType._("11220", "서초구", ProvinceType.seoul),
    DistrictType._("11230", "강남구", ProvinceType.seoul),
    DistrictType._("11240", "송파구", ProvinceType.seoul),
    DistrictType._("11250", "강동구", ProvinceType.seoul),
  ];

  static const List<DistrictType> busan = [
    DistrictType._("21010", "중구", ProvinceType.busan),
    DistrictType._("21020", "서구", ProvinceType.busan),
    DistrictType._("21030", "동구", ProvinceType.busan),
    DistrictType._("21040", "영도구", ProvinceType.busan),
    DistrictType._("21050", "부산진구", ProvinceType.busan),
    DistrictType._("21060", "동래구", ProvinceType.busan),
    DistrictType._("21070", "남구", ProvinceType.busan),
    DistrictType._("21080", "북구", ProvinceType.busan),
    DistrictType._("21090", "해운대구", ProvinceType.busan),
    DistrictType._("21100", "사하구", ProvinceType.busan),
    DistrictType._("21110", "금정구", ProvinceType.busan),
    DistrictType._("21120", "강서구", ProvinceType.busan),
    DistrictType._("21130", "연제구", ProvinceType.busan),
    DistrictType._("21140", "수영구", ProvinceType.busan),
    DistrictType._("21150", "사상구", ProvinceType.busan),
    DistrictType._("21310", "기장군", ProvinceType.busan),
  ];

  static const List<DistrictType> daegu = [
    DistrictType._("22010", "중구", ProvinceType.daegu),
    DistrictType._("22020", "동구", ProvinceType.daegu),
    DistrictType._("22030", "서구", ProvinceType.daegu),
    DistrictType._("22040", "남구", ProvinceType.daegu),
    DistrictType._("22050", "북구", ProvinceType.daegu),
    DistrictType._("22060", "수성구", ProvinceType.daegu),
    DistrictType._("22070", "달서구", ProvinceType.daegu),
    DistrictType._("22310", "달성군", ProvinceType.daegu),
    DistrictType._("22330", "군위군", ProvinceType.daegu),
  ];

  static const List<DistrictType> incheon = [
    DistrictType._("23010", "중구", ProvinceType.incheon),
    DistrictType._("23020", "동구", ProvinceType.incheon),
    DistrictType._("23040", "미추홀구", ProvinceType.incheon),
    DistrictType._("23050", "연수구", ProvinceType.incheon),
    DistrictType._("23060", "남동구", ProvinceType.incheon),
    DistrictType._("23070", "부평구", ProvinceType.incheon),
    DistrictType._("23080", "계양구", ProvinceType.incheon),
    DistrictType._("23090", "서구", ProvinceType.incheon),
    DistrictType._("23310", "강화군", ProvinceType.incheon),
    DistrictType._("23320", "옹진군", ProvinceType.incheon),
  ];

  static const List<DistrictType> gwangju = [
    DistrictType._("24010", "동구", ProvinceType.gwangju),
    DistrictType._("24020", "서구", ProvinceType.gwangju),
    DistrictType._("24030", "남구", ProvinceType.gwangju),
    DistrictType._("24040", "북구", ProvinceType.gwangju),
    DistrictType._("24050", "광산구", ProvinceType.gwangju),
  ];

  static const List<DistrictType> daejeon = [
    DistrictType._("25010", "동구", ProvinceType.daejeon),
    DistrictType._("25020", "중구", ProvinceType.daejeon),
    DistrictType._("25030", "서구", ProvinceType.daejeon),
    DistrictType._("25040", "유성구", ProvinceType.daejeon),
    DistrictType._("25050", "대덕구", ProvinceType.daejeon),
  ];

  static const List<DistrictType> ulsan = [
    DistrictType._("26010", "중구", ProvinceType.ulsan),
    DistrictType._("26020", "남구", ProvinceType.ulsan),
    DistrictType._("26030", "동구", ProvinceType.ulsan),
    DistrictType._("26040", "북구", ProvinceType.ulsan),
    DistrictType._("26310", "울주군", ProvinceType.ulsan),
  ];

  static const List<DistrictType> sejong = [
    DistrictType._("29011", "조치원읍", ProvinceType.sejong),
    DistrictType._("29021", "연기면", ProvinceType.sejong),
    DistrictType._("29022", "연동면", ProvinceType.sejong),
    DistrictType._("29023", "부강면", ProvinceType.sejong),
    DistrictType._("29024", "금남면", ProvinceType.sejong),
    DistrictType._("29025", "장군면", ProvinceType.sejong),
    DistrictType._("29026", "연서면", ProvinceType.sejong),
    DistrictType._("29027", "전의면", ProvinceType.sejong),
    DistrictType._("29028", "전동면", ProvinceType.sejong),
    DistrictType._("29029", "소정면", ProvinceType.sejong),
    DistrictType._("29031", "한솔동", ProvinceType.sejong),
    DistrictType._("29032", "새롬동", ProvinceType.sejong),
    DistrictType._("29033", "나성동", ProvinceType.sejong),
    DistrictType._("29034", "다정동", ProvinceType.sejong),
    DistrictType._("29035", "도담동", ProvinceType.sejong),
    DistrictType._("29036", "어진동", ProvinceType.sejong),
    DistrictType._("29037", "해밀동", ProvinceType.sejong),
    DistrictType._("29038", "아름동", ProvinceType.sejong),
    DistrictType._("29039", "종촌동", ProvinceType.sejong),
    DistrictType._("29040", "고운동", ProvinceType.sejong),
    DistrictType._("29041", "보람동", ProvinceType.sejong),
    DistrictType._("29042", "대평동", ProvinceType.sejong),
    DistrictType._("29043", "소담동", ProvinceType.sejong),
    DistrictType._("29044", "반곡동", ProvinceType.sejong),
  ];

  static const List<DistrictType> gyeonggi = [
    DistrictType._("31010", "수원시 장안구", ProvinceType.gyeonggi),
    DistrictType._("31020", "수원시 권선구", ProvinceType.gyeonggi),
    DistrictType._("31030", "수원시 팔달구", ProvinceType.gyeonggi),
    DistrictType._("31040", "수원시 영통구", ProvinceType.gyeonggi),
    DistrictType._("31050", "성남시 수정구", ProvinceType.gyeonggi),
    DistrictType._("31060", "성남시 중원구", ProvinceType.gyeonggi),
    DistrictType._("31070", "성남시 분당구", ProvinceType.gyeonggi),
    DistrictType._("31080", "의정부시", ProvinceType.gyeonggi),
    DistrictType._("31090", "안양시 만안구", ProvinceType.gyeonggi),
    DistrictType._("31100", "안양시 동안구", ProvinceType.gyeonggi),
    DistrictType._("31110", "부천시", ProvinceType.gyeonggi),
    DistrictType._("31120", "광명시", ProvinceType.gyeonggi),
    DistrictType._("31130", "평택시", ProvinceType.gyeonggi),
    DistrictType._("31140", "동두천시", ProvinceType.gyeonggi),
    DistrictType._("31150", "안산시 상록구", ProvinceType.gyeonggi),
    DistrictType._("31160", "안산시 단원구", ProvinceType.gyeonggi),
    DistrictType._("31170", "고양시 덕양구", ProvinceType.gyeonggi),
    DistrictType._("31180", "고양시 일산동구", ProvinceType.gyeonggi),
    DistrictType._("31190", "고양시 일산서구", ProvinceType.gyeonggi),
    DistrictType._("31200", "과천시", ProvinceType.gyeonggi),
    DistrictType._("31210", "구리시", ProvinceType.gyeonggi),
    DistrictType._("31220", "남양주시", ProvinceType.gyeonggi),
    DistrictType._("31230", "오산시", ProvinceType.gyeonggi),
    DistrictType._("31240", "시흥시", ProvinceType.gyeonggi),
    DistrictType._("31250", "군포시", ProvinceType.gyeonggi),
    DistrictType._("31260", "의왕시", ProvinceType.gyeonggi),
    DistrictType._("31270", "하남시", ProvinceType.gyeonggi),
    DistrictType._("31280", "용인시 처인구", ProvinceType.gyeonggi),
    DistrictType._("31290", "용인시 기흥구", ProvinceType.gyeonggi),
    DistrictType._("31300", "용인시 수지구", ProvinceType.gyeonggi),
    DistrictType._("31310", "파주시", ProvinceType.gyeonggi),
    DistrictType._("31320", "이천시", ProvinceType.gyeonggi),
    DistrictType._("31330", "안성시", ProvinceType.gyeonggi),
    DistrictType._("31340", "김포시", ProvinceType.gyeonggi),
    DistrictType._("31350", "화성시", ProvinceType.gyeonggi),
    DistrictType._("31360", "광주시", ProvinceType.gyeonggi),
    DistrictType._("31370", "양주시", ProvinceType.gyeonggi),
    DistrictType._("31380", "포천시", ProvinceType.gyeonggi),
    DistrictType._("31390", "여주시", ProvinceType.gyeonggi),
    DistrictType._("31410", "연천군", ProvinceType.gyeonggi),
    DistrictType._("31420", "가평군", ProvinceType.gyeonggi),
    DistrictType._("31430", "양평군", ProvinceType.gyeonggi),
  ];

  static const List<DistrictType> gangwon = [
    DistrictType._("32010", "춘천시", ProvinceType.gangwon),
    DistrictType._("32020", "원주시", ProvinceType.gangwon),
    DistrictType._("32030", "강릉시", ProvinceType.gangwon),
    DistrictType._("32040", "동해시", ProvinceType.gangwon),
    DistrictType._("32050", "태백시", ProvinceType.gangwon),
    DistrictType._("32060", "속초시", ProvinceType.gangwon),
    DistrictType._("32070", "삼척시", ProvinceType.gangwon),
    DistrictType._("32310", "홍천군", ProvinceType.gangwon),
    DistrictType._("32320", "횡성군", ProvinceType.gangwon),
    DistrictType._("32330", "영월군", ProvinceType.gangwon),
    DistrictType._("32340", "평창군", ProvinceType.gangwon),
    DistrictType._("32350", "정선군", ProvinceType.gangwon),
    DistrictType._("32360", "철원군", ProvinceType.gangwon),
    DistrictType._("32370", "화천군", ProvinceType.gangwon),
    DistrictType._("32380", "양구군", ProvinceType.gangwon),
    DistrictType._("32390", "인제군", ProvinceType.gangwon),
    DistrictType._("32400", "고성군", ProvinceType.gangwon),
    DistrictType._("32410", "양양군", ProvinceType.gangwon),
  ];

  static const List<DistrictType> chungbuk = [
    DistrictType._("33010", "청주시 상당구", ProvinceType.chungbuk),
    DistrictType._("33020", "청주시 서원구", ProvinceType.chungbuk),
    DistrictType._("33030", "청주시 흥덕구", ProvinceType.chungbuk),
    DistrictType._("33040", "청주시 청원구", ProvinceType.chungbuk),
    DistrictType._("33050", "충주시", ProvinceType.chungbuk),
    DistrictType._("33060", "제천시", ProvinceType.chungbuk),
    DistrictType._("33310", "보은군", ProvinceType.chungbuk),
    DistrictType._("33320", "옥천군", ProvinceType.chungbuk),
    DistrictType._("33330", "영동군", ProvinceType.chungbuk),
    DistrictType._("33340", "진천군", ProvinceType.chungbuk),
    DistrictType._("33350", "괴산군", ProvinceType.chungbuk),
    DistrictType._("33360", "음성군", ProvinceType.chungbuk),
    DistrictType._("33370", "단양군", ProvinceType.chungbuk),
    DistrictType._("33380", "증평군", ProvinceType.chungbuk),
  ];

  static const List<DistrictType> chungnam = [
    DistrictType._("34010", "천안시 동남구", ProvinceType.chungnam),
    DistrictType._("34020", "천안시 서북구", ProvinceType.chungnam),
    DistrictType._("34030", "공주시", ProvinceType.chungnam),
    DistrictType._("34040", "보령시", ProvinceType.chungnam),
    DistrictType._("34050", "아산시", ProvinceType.chungnam),
    DistrictType._("34060", "서산시", ProvinceType.chungnam),
    DistrictType._("34070", "논산시", ProvinceType.chungnam),
    DistrictType._("34080", "계룡시", ProvinceType.chungnam),
    DistrictType._("34090", "당진시", ProvinceType.chungnam),
    DistrictType._("34310", "금산군", ProvinceType.chungnam),
    DistrictType._("34330", "부여군", ProvinceType.chungnam),
    DistrictType._("34340", "서천군", ProvinceType.chungnam),
    DistrictType._("34350", "청양군", ProvinceType.chungnam),
    DistrictType._("34360", "홍성군", ProvinceType.chungnam),
    DistrictType._("34370", "예산군", ProvinceType.chungnam),
    DistrictType._("34380", "태안군", ProvinceType.chungnam),
  ];

  static const List<DistrictType> jeonbuk = [
    DistrictType._("35010", "전주시 완산구", ProvinceType.jeonbuk),
    DistrictType._("35020", "전주시 덕진구", ProvinceType.jeonbuk),
    DistrictType._("35030", "군산시", ProvinceType.jeonbuk),
    DistrictType._("35040", "익산시", ProvinceType.jeonbuk),
    DistrictType._("35050", "정읍시", ProvinceType.jeonbuk),
    DistrictType._("35060", "남원시", ProvinceType.jeonbuk),
    DistrictType._("35070", "김제시", ProvinceType.jeonbuk),
    DistrictType._("35310", "완주군", ProvinceType.jeonbuk),
    DistrictType._("35320", "진안군", ProvinceType.jeonbuk),
    DistrictType._("35330", "무주군", ProvinceType.jeonbuk),
    DistrictType._("35340", "장수군", ProvinceType.jeonbuk),
    DistrictType._("35350", "임실군", ProvinceType.jeonbuk),
    DistrictType._("35360", "순창군", ProvinceType.jeonbuk),
    DistrictType._("35370", "고창군", ProvinceType.jeonbuk),
    DistrictType._("35380", "부안군", ProvinceType.jeonbuk),
  ];

  static const List<DistrictType> jeonnam = [
    DistrictType._("36010", "목포시", ProvinceType.jeonnam),
    DistrictType._("36020", "여수시", ProvinceType.jeonnam),
    DistrictType._("36030", "순천시", ProvinceType.jeonnam),
    DistrictType._("36040", "나주시", ProvinceType.jeonnam),
    DistrictType._("36060", "광양시", ProvinceType.jeonnam),
    DistrictType._("36310", "담양군", ProvinceType.jeonnam),
    DistrictType._("36320", "곡성군", ProvinceType.jeonnam),
    DistrictType._("36330", "구례군", ProvinceType.jeonnam),
    DistrictType._("36350", "고흥군", ProvinceType.jeonnam),
    DistrictType._("36360", "보성군", ProvinceType.jeonnam),
    DistrictType._("36370", "화순군", ProvinceType.jeonnam),
    DistrictType._("36380", "장흥군", ProvinceType.jeonnam),
    DistrictType._("36390", "강진군", ProvinceType.jeonnam),
    DistrictType._("36400", "해남군", ProvinceType.jeonnam),
    DistrictType._("36410", "영암군", ProvinceType.jeonnam),
    DistrictType._("36420", "무안군", ProvinceType.jeonnam),
    DistrictType._("36430", "함평군", ProvinceType.jeonnam),
    DistrictType._("36440", "영광군", ProvinceType.jeonnam),
    DistrictType._("36450", "장성군", ProvinceType.jeonnam),
    DistrictType._("36460", "완도군", ProvinceType.jeonnam),
    DistrictType._("36470", "진도군", ProvinceType.jeonnam),
    DistrictType._("36480", "신안군", ProvinceType.jeonnam),
  ];

  static const List<DistrictType> gyeongbuk = [
    DistrictType._("37010", "포항시 남구", ProvinceType.gyeongbuk),
    DistrictType._("37020", "포항시 북구", ProvinceType.gyeongbuk),
    DistrictType._("37030", "경주시", ProvinceType.gyeongbuk),
    DistrictType._("37040", "김천시", ProvinceType.gyeongbuk),
    DistrictType._("37050", "안동시", ProvinceType.gyeongbuk),
    DistrictType._("37060", "구미시", ProvinceType.gyeongbuk),
    DistrictType._("37070", "영주시", ProvinceType.gyeongbuk),
    DistrictType._("37080", "영천시", ProvinceType.gyeongbuk),
    DistrictType._("37090", "상주시", ProvinceType.gyeongbuk),
    DistrictType._("37100", "문경시", ProvinceType.gyeongbuk),
    DistrictType._("37110", "경산시", ProvinceType.gyeongbuk),
    DistrictType._("37310", "의성군", ProvinceType.gyeongbuk),
    DistrictType._("37320", "청송군", ProvinceType.gyeongbuk),
    DistrictType._("37330", "영양군", ProvinceType.gyeongbuk),
    DistrictType._("37340", "영덕군", ProvinceType.gyeongbuk),
    DistrictType._("37350", "청도군", ProvinceType.gyeongbuk),
    DistrictType._("37360", "고령군", ProvinceType.gyeongbuk),
    DistrictType._("37370", "성주군", ProvinceType.gyeongbuk),
    DistrictType._("37380", "칠곡군", ProvinceType.gyeongbuk),
    DistrictType._("37390", "예천군", ProvinceType.gyeongbuk),
    DistrictType._("37400", "봉화군", ProvinceType.gyeongbuk),
    DistrictType._("37410", "울진군", ProvinceType.gyeongbuk),
    DistrictType._("37420", "울릉군", ProvinceType.gyeongbuk),
  ];

  static const List<DistrictType> gyeongnam = [
    DistrictType._("38010", "창원시 의창구", ProvinceType.gyeongnam),
    DistrictType._("38020", "창원시 성산구", ProvinceType.gyeongnam),
    DistrictType._("38030", "창원시 마산합포구", ProvinceType.gyeongnam),
    DistrictType._("38040", "창원시 마산회원구", ProvinceType.gyeongnam),
    DistrictType._("38050", "창원시 진해구", ProvinceType.gyeongnam),
    DistrictType._("38060", "진주시", ProvinceType.gyeongnam),
    DistrictType._("38070", "통영시", ProvinceType.gyeongnam),
    DistrictType._("38080", "사천시", ProvinceType.gyeongnam),
    DistrictType._("38090", "김해시", ProvinceType.gyeongnam),
    DistrictType._("38100", "밀양시", ProvinceType.gyeongnam),
    DistrictType._("38110", "거제시", ProvinceType.gyeongnam),
    DistrictType._("38120", "양산시", ProvinceType.gyeongnam),
    DistrictType._("38310", "의령군", ProvinceType.gyeongnam),
    DistrictType._("38320", "함안군", ProvinceType.gyeongnam),
    DistrictType._("38330", "창녕군", ProvinceType.gyeongnam),
    DistrictType._("38340", "고성군", ProvinceType.gyeongnam),
    DistrictType._("38350", "남해군", ProvinceType.gyeongnam),
    DistrictType._("38360", "하동군", ProvinceType.gyeongnam),
    DistrictType._("38370", "산청군", ProvinceType.gyeongnam),
    DistrictType._("38380", "함양군", ProvinceType.gyeongnam),
    DistrictType._("38390", "거창군", ProvinceType.gyeongnam),
    DistrictType._("38400", "합천군", ProvinceType.gyeongnam),
  ];

  static const List<DistrictType> jeju = [
    DistrictType._("39010", "제주시", ProvinceType.jeju),
    DistrictType._("39020", "서귀포시", ProvinceType.jeju),
  ];

  get address => null;

  static const List<DistrictType> _all = [
    ...seoul,
    ...busan,
    ...daegu,
    ...incheon,
    ...gwangju,
    ...daejeon,
    ...ulsan,
    ...sejong,
    ...gyeonggi,
    ...gangwon,
    ...chungbuk,
    ...chungnam,
    ...jeonbuk,
    ...jeonnam,
    ...gyeongbuk,
    ...gyeongnam,
  ];

  static final Map<String, DistrictType> _index = {
    for (final d in _all) d.code: d,
  };

  static DistrictType fromCode(String code) => _index[code] ?? seoul.first;
}
